### ISSUE TITLE
Migrate to `@vue/reactivity` as peer dependency

### ISSUE THREAD

**Issue by husayt** [johannschopplich/vue-signals#1]
This library doesn't even need all of Vue3 and can work with just @vue3/reactivity 
https://www.npmjs.com/package/@vue/reactivity

That will make it vue independent, smaller and even better for use with other frameworks

**Comment by johannschopplich** [comment]
Haha, indeed. This package is merely for educational purposes. Please read the [FAQ](https://github.com/johannschopplich/vue-signals#why-though). Thanks!

**Comment by husayt** [comment]
Thanks.

even if educational, it's really interesting to find common reactivity base allowing to write reusable composible blocks
